
import { CategoryType, Contact } from './types';

export const CATEGORIES = [
  { id: 'urgences', name: 'Urgences', icon: '🚨', type: CategoryType.URGENCES },
  { id: 'sante', name: 'Santé', icon: '🏥', type: CategoryType.SANTE },
  { id: 'depannage', name: 'Dépannage', icon: '🛠️', type: CategoryType.DEPANNAGE },
  { id: 'quotidien', name: 'Services', icon: '📦', type: CategoryType.QUOTIDIEN },
  { id: 'admin', name: 'Admin', icon: '🏛️', type: CategoryType.ADMINISTRATION },
];

export const MOCK_CONTACTS: Contact[] = [
  // Urgences
  {
    id: 'u1',
    name: 'SAMU Bénin',
    category: CategoryType.URGENCES,
    subCategory: 'Ambulance',
    phone: '95361102',
    location: 'National',
    city: 'Tout le Bénin',
    description: 'Service d\'Aide Médicale Urgente du Bénin.',
    isVerified: true,
    isPremium: false,
  },
  {
    id: 'u2',
    name: 'Police Secours',
    category: CategoryType.URGENCES,
    subCategory: 'Police',
    phone: '117',
    location: 'National',
    city: 'Tout le Bénin',
    description: 'Numéro d\'urgence de la police républicaine.',
    isVerified: true,
    isPremium: false,
  },
  {
    id: 'u3',
    name: 'Sapeurs-Pompiers',
    category: CategoryType.URGENCES,
    subCategory: 'Pompiers',
    phone: '118',
    location: 'National',
    city: 'Tout le Bénin',
    description: 'Protection civile et incendies.',
    isVerified: true,
    isPremium: false,
  },
  // Santé
  {
    id: 's1',
    name: 'Pharmacie Camp Guézo',
    category: CategoryType.SANTE,
    subCategory: 'Pharmacie',
    phone: '21312345',
    whatsapp: '22997000000',
    location: 'Camp Guézo, Cotonou',
    city: 'Cotonou',
    description: 'Pharmacie ouverte 24h/24 selon planning de garde.',
    isVerified: true,
    isPremium: true,
    rating: 4.8,
    reviewsCount: 154,
  },
  {
    id: 's2',
    name: 'CNHU-HKM Cotonou',
    category: CategoryType.SANTE,
    subCategory: 'Hôpital',
    phone: '21300155',
    location: 'Cadjehoun, Cotonou',
    city: 'Cotonou',
    description: 'Centre National Hospitalier Universitaire Hubert Koutoukou Maga.',
    isVerified: true,
    isPremium: false,
  },
  // Dépannage
  {
    id: 'd1',
    name: 'Mecanicien Pro Cotonou',
    category: CategoryType.DEPANNAGE,
    subCategory: 'Mécanique Auto',
    phone: '97451234',
    whatsapp: '22997451234',
    location: 'Akpakpa, Cotonou',
    city: 'Cotonou',
    description: 'Spécialiste moteur essence et diesel. Dépannage rapide.',
    isVerified: true,
    isPremium: true,
    rating: 4.5,
    reviewsCount: 42,
  },
  {
    id: 'd2',
    name: 'Electricité Bâtiment Bénin',
    category: CategoryType.DEPANNAGE,
    subCategory: 'Electricien',
    phone: '95123456',
    whatsapp: '22995123456',
    location: 'Calavi Kpota',
    city: 'Abomey-Calavi',
    description: 'Installation et dépannage électrique 7j/7.',
    isVerified: true,
    isPremium: false,
    rating: 4.2,
    reviewsCount: 12,
  },
  // Quotidien
  {
    id: 'q1',
    name: 'Gaz Service Rapide',
    category: CategoryType.QUOTIDIEN,
    subCategory: 'Gaz',
    phone: '90010203',
    whatsapp: '22990010203',
    location: 'Etoile Rouge, Cotonou',
    city: 'Cotonou',
    description: 'Livraison de bouteilles de gaz à domicile.',
    isVerified: true,
    isPremium: true,
    rating: 4.9,
    reviewsCount: 89,
  },
];
